services:
  - type: web
    name: jomar-soliman-portfolio
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      npm install
      npm run build
    startCommand: php artisan serve --host=0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:LCX30VHSkVTeDyKwUrw8qaSOK5bsqwqTWJNnmjm7pwE=
      - key: APP_URL
        value: https://jomar-soliman-portfolio.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: localhost
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: my_portfolio
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value:
